### ISSUE TITLE
Protect Media file for membership

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#13]
specifically for "this month's workbook"

**Comment by oakwoodgates** [comment]
potential solution - https://www.woothemes.com/products/woocommerce-subscription-downloads/

**Comment by earthwitch** [comment]
will look at it. also finding out how Herbiary protects these when selling online (they are available through the Herbiary store).

**Comment by earthwitch** [comment]
Can't figure out how to use Herbiary's method-- through Shopify-- but I spoke with a friend and she said she simply uses really stupid file names that no one would ever guess and blocks search engines from the page (which the membership site should already do, right?).
