### ISSUE TITLE
(future) Unsub

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#14]
link Unsubscribe in Woo to Convert Kit

**Comment by earthwitch** [comment]
let's talk about what it will take to get this done. Convert Kit works with Zapier and I'm wondering if that's the link to make it happen.

**Comment by oakwoodgates** [comment]
Cool, yea if you're open to Zapier that's probably the easiest/fastest/short-term-cheapest way to do it.

**Comment by earthwitch** [comment]
I don't know how to use zapier but it's good in theory. :)

**Comment by oakwoodgates** [comment]
Looks like they have everything available - https://zapier.com/zapbook/convertkit/woocommerce/ - under "Make your own Zap with triggers + actions".

**Comment by earthwitch** [comment]
we got this done in Zapier
