### ISSUE TITLE
tweaks to Hub

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#16]
wow-- this page has been a bitch to set-up. Almost there. :)

tweaks:
1. the dual logos wasn't working for me. Can you either center logo OR use the secondary logo for "my account" (see #2)
2. "my account" and "shop" are hard to see/read can the font be bigger OR put shop in the main menu and put my account where 2nd logo was 
3. add a down arrow (like this > but down facing) after "my account"-- see original mock-up
4. move menu to center
5. does the "Badges" app come with something that keeps a tab on how many points someone has accumulated?

**Comment by oakwoodgates** [comment]
1. I think center would be best.
2. Upped the size 1px. I'm not a big fan of the my-account in that second logo spot.
3. ...
4. ?
5. yes

**Comment by earthwitch** [comment]
hmmmm... Hub tweaks not showing for me even with a hard refresh (so I can't comment yet!).

How do we make the badges point total show-up?

**Comment by oakwoodgates** [comment]
I made you a shortcode to display a users point total

[mtoll_user_points]

**Comment by earthwitch** [comment]
Yay! And I wanna make sure I understand--- if I put this in a widget next
to the badges in the hub will it display the users current point total?

**Comment by oakwoodgates** [comment]
Yep, just pop that in anywhere. It only outputs the number.

**Comment by earthwitch** [comment]
Cool.

Can the menu be centered?
