### ISSUE TITLE
tweaks to menu changes on home page

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#17]
Don't know if the top menu needs to match what's in the Hub....
1. But for the homepage SHOP is already in the main menu and LOGIN would be better than "my account."
2. Also-- too small and hard to read. Like the green bar though. :)
3. Can we get the end of the top bar menu to line up with the end of the witchy.wise.well. logo?

**Comment by oakwoodgates** [comment]
1. Should we pull shop off of the main menu then?
2. I bumped the sizing up a pixel, don't wanna go too big...but lmk if that works.
3. If you notice, the right side of the top bar lines up with the right side of the search icon. It's the witchy.wise logo that's the culprit...it has some extra white space on the side that needs cropped off.

**Comment by earthwitch** [comment]
Will crop extra white off logos-- was using it to get logos to line up with menu!
1. Let's bump shop off the top bar menu. 
2. Can "my account" say log in on all non-logged in pages and say "my account" after log in?

**Comment by earthwitch** [comment]
Actually -- a second thought.

Let's keep shop in the top bar IF we can add the Witch Camp LOGO to the menu bar. People are writing to say "where's Witch Camp" so that might be a smart move.

**Comment by oakwoodgates** [comment]
In that case, I would probably do 
- Shop / Witch Camp / My Account 
  Or 
- Shop / My Account / ~Witch Camp~ <--in a different color or bold or something

**Comment by oakwoodgates** [comment]
^I would do that in the top bar.

I'm not sure how that logo would go in the menu bar? Instead of witchy.wise.well?

**Comment by earthwitch** [comment]
I want to keep witchy.wise.well. for marketing reasons....

Could you try a Witch Camp link in the top menu in 5b316d?
