### ISSUE TITLE
mobile tweaks

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#18]
1. header image and text as per our discussion
2. Logo looks off center to me-- looks too far left.

**Comment by oakwoodgates** [comment]
Header image should be good now. Def loads a lot faster

Logos have an uneven amount of white space on the sides, so that's kinda messing up centering.

**Comment by earthwitch** [comment]
will work on logos.

let's look at mobile view together--- it is WAY better (and might be as good as it gets given the template) but I want to show you on my phone and see if we can tweak some of the hard to read stuff.

Also TRUTH TOOLS in mobile is justified Left and all other headers are centered. :)

**Comment by oakwoodgates** [comment]
ok, sure. Get a hold of me if you want to get together quick today. Also, I don't know what the truth tools is you're talking about :)

**Comment by earthwitch** [comment]
it's the special flower oracle section. The headline reads "Truth Tools"
