### ISSUE TITLE
Flow for setting up points and badges

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#19]
Instead of starting with a badge:

Badge #1 = Butterfly. To achieve:
- watch the video on the Hub page and click through to FAQ section (let's not include signing up for FB because some of my folks hate it)

After that 13 points moves you up a level until you hit bear-- I'll be coming up with something different for bear and owl.

Award points for:  
- commenting on blog posts- 2 points
- attending new moon call - 4 points
- commenting in the Luna Lounge - 2 points

**Comment by oakwoodgates** [comment]
I coded a little thing last night so a little extra functionality is ready to go :) Looks like there's just a couple of more badges that need configured. As soon as that's done, I'll fill in the numbers for you. Might have a couple of questions.

**Comment by earthwitch** [comment]
Cool-- I thought I had the all set-up but I had messed them up a little. Will do now and let you know when it's done.

**Comment by earthwitch** [comment]
Badges are ready!

**Comment by oakwoodgates** [comment]
ok, so it's:
-Butterfly (after the video/faq)
-dragonfly (at 13 points)
-deer (at 26 points)
-beaver (at 39 points)
-dolphin (at 52 points)
-wolf (at 65 points)
-raven (at 78 points)

correct?

**Comment by earthwitch** [comment]
correct!
