### ISSUE TITLE
title on login page

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#20]
![screen shot 2016-06-15 at 5 04 42 pm](https://cloud.githubusercontent.com/assets/19781580/16097357/7153be64-331b-11e6-9af8-34d69e88e1ff.png)

https://maiatoll.com/content-restricted/?r=13649

See how it say MToll Landing Login before the Login? Can that disappear?

**Comment by oakwoodgates** [comment]
I removed it, but if you want to add a title again, you can do from the Sign In page
