### ISSUE TITLE
to launch

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#21]
1.   Want to change the minimum price to $8 (because I decided to include the monthly workbooks which sell for $8).
-  I changed all the copy but can't figure out how to change the minimum.
-  Also can the fill-in-the-blank line be BLAN (currently it says $6). I'd rather not suggest to people that they low-ball.
1. There is a free membership page floating around that someone managed to find (my people are ON IT! See screen shot). Can we delete?

![screen shot 2016-06-17 at 8 30 26 am](https://cloud.githubusercontent.com/assets/19781580/16151247/e9b54efa-3469-11e6-81cf-ed9020f772ad.png)

**Comment by oakwoodgates** [comment]
Sure, I can show you where to change the price. It's in wp-admin->products->"the product". There isn't a way to (easily) not make that price show up.
