### ISSUE TITLE
Change "INSTAGRAM SLIDER" text

### ISSUE THREAD

**Issue by oakwoodgates** [oakwoodgates/mtoll#22]
What do you think...that could probably be better? Do you know where to change that?

I assigned this to you (that's what the collaborator invitation was for)...so feel free to close it out whenever.

**Comment by earthwitch** [comment]
I do know where to make changes to the Instagram slider--- but I don't understand what the problem is :)

**Comment by oakwoodgates** [comment]
I thought it was kinda "demo theme(ish)" sounding...mostly the "slider" word. Maybe "Maia on Instagram" or "Check me out on IG" or something...but if you like it the way it is, that's fine too :)

**Comment by earthwitch** [comment]
Good catch! I had set that up a long time ago and changes the title and
then I had to re-install it and forgot the title change. :)
