### ISSUE TITLE
Witch Camp Community page

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#29]
I have the "landing page options" set to "social, bottom" but it's showing everything.

What am I doing wrong? :)

**Comment by oakwoodgates** [comment]
Nothing :) Those options only work for "landing page template".

**Comment by earthwitch** [comment]
then why is it all shoved over to the left?

**Comment by earthwitch** [comment]
can I change it to Landing Page template or will that screw things up now?
