### ISSUE TITLE
uh-oh

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#31]
I built out the library page-- see attached-- but when I go to view by clicking preview it I get a 404 error.

![screen shot 2016-06-17 at 5 09 03 pm](https://cloud.githubusercontent.com/assets/19781580/16164841/5cacd812-34ae-11e6-8f55-68c93eb2b090.png)

**Comment by oakwoodgates** [comment]
Not sure, I can def view it on the front end though.

**Comment by earthwitch** [comment]
guess that's all that matters :)
