### ISSUE TITLE
"Luna Lounge"in menu bounces

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#33]
back to the Hub when it's closed.

can it bounce to a pop up or landing page so people don't get confused? I can just post the closed sign and the hours.

**Comment by oakwoodgates** [comment]
If they try to view a lounge (where the menu is linking to), and it's closed, they get redirected to a page set in your options panel (which could be a lounge closed page). 

It would be a good idea in the future to maybe style that menu link different for open/closed or add a pop up if closed.

**Comment by earthwitch** [comment]
Did it!

(Make me stupid happy to be able to do this shit!).
