### ISSUE TITLE
secondary menu for signed in members

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#4]
also note the header change
![witch camp community](https://cloud.githubusercontent.com/assets/19781580/15835465/22be180e-2bfe-11e6-85ca-5a87506bb037.jpg)

**Comment by oakwoodgates** [comment]
Just to double check, this header will show for:
- Lounges
- Premium stuff (library, downloads)
- The Hub

correct?

**Comment by oakwoodgates** [comment]
Also, this menu will also replace the default mobile menu on these pages, correct?

**Comment by earthwitch** [comment]
correct on all counts

created the FAQ as in above menu-- calling it Community Handbook. Find it at www.maiatoll.com/handbook

**Comment by oakwoodgates** [comment]
Ok cool. That's what it's set up for now. 

For the menu - wp-admin->appearance->menus->WC Menu
Logo options are in your options page. I couldn't find the logo in the media folder, so there's a placeholder logo there now.

Will close this for now. lmk
