### ISSUE TITLE
Tell Maia how to turn off sign-up page!

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#42]
Do I just make it a draft again? It seems like I would want to redirect people who followed the link.....

**Comment by oakwoodgates** [comment]
Yep, either (or both) or those. I'm a fan of the redirect option.

**Comment by oakwoodgates** [comment]
lmk if you have any questions about this

**Comment by oakwoodgates** [comment]
Didn't mean to close it out, but feel free to close if you're good here.

**Comment by earthwitch** [comment]
I just google search how to do a redirect in Word Press. According to Google I need to download a plug-in. Just want to check with you before I do this so you don't have to undo it. :)

**Comment by oakwoodgates** [comment]
I was thinking you had a redirect plugin at one point. If not, or if you
don't like that one, let's get another one.

I remember way back at the start of this (during the image issues) I had
mentioned the need to (eventually) set up a redirect system for all of your
outbound links, as well as stuff like this...lmk if you want to go over
that again.

But yea...feel free to grab any redirect plugin that looks like it will do
the job.
