### ISSUE TITLE
adjust header area for mobile

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#7]
AFTER the membership stuff is complete. :)

Header photo coming to you via DropBox

**Comment by earthwitch** [comment]
Cool guy I know who is coincidentally using the same theme to build out his wife's site just sent this:

> I was able to fix the problems I was having with the slider text and button by adjusting the mobile only CSS and putting that adjusted code in the Custom Code section of the Customize area for the theme. 
> 
> I've fixed things for the phone size screens but still need to do it for the ipad sized screens. 
> 
> For the phone sized bits, maybe tell your coder to mess around with the CSS selectors for the penci slider in the style.css file that starts with:
> 
> @media only screen and (max-width: 767px)
> 
> there's another section for the slightly larger screens. He likely has already been doing that, but that's how I fixed the text issues for the slider on my phone. (Of course, I grabbed the code from the style.css file and adjusted it in the "custom code" area in the Customize interface for the theme (which is the same as adding your own custom CSS to a style.css file in the child theme.)

**Comment by oakwoodgates** [comment]
The image in dropbox doesn't have the flowery background (like the current image). Should we make that happen, or...?

**Comment by earthwitch** [comment]
sent you the image again via Dropbox. Dunno why but DB deleted the other image.

**Comment by oakwoodgates** [comment]
Should be good now. Let's consolidate this discussion into #18
