### ISSUE TITLE
On Special Witch Camp Membership page

### ISSUE THREAD

**Issue by earthwitch** [oakwoodgates/mtoll#9]
After the name your own price you have to Update Cart by clicking a button. Make more user friendly (you said something about an automatic cart update through javascript). A giant arrow pointing to the button will work too. :)

**Comment by earthwitch** [comment]
why don't we launch without this and see what happens? In the email about the special membership I told people to tag me this weekend on FB if they are having trouble. If people are confused, we could make the button neon or something. :)

**Comment by oakwoodgates** [comment]
Sounds good. I'll close this for now but feel free to reopen if we need to look at it.
